# Generated by Django 3.2.5 on 2022-07-29 05:15

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0002_auto_20220729_0423'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='author',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=55, unique=True),
        ),
    ]
