# Generated by Django 3.2.5 on 2022-07-29 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0003_auto_20220729_0515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='username',
        ),
    ]
