# Generated by Django 4.0.6 on 2022-07-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0006_auto_20220730_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
